name: Focally
options:
  bundleIdPrefix: app.focally
  xcodeVersion: "15.0"
  deploymentTarget:
    macOS: "14.0"
  generateEmptyDirectories: true
  settings:
    base:
      FONT_PROCESSORS: [ttf]

settings:
  base:
    SWIFT_VERSION: "5.9"
    PRODUCT_BUNDLE_IDENTIFIER: app.focally.mac
    MARKETING_VERSION: "0.6.2"
    CURRENT_PROJECT_VERSION: "11"

targets:
  Focally:
    type: application
    platform: macOS
    sources:
      - Focally
      - path: Focally/DesignSystem
        type: folder
      - path: Focally/Views/Navigation
        type: folder
      - path: Focally/Views/Timer
        type: folder
      - path: Focally/Views/Tasks
        type: folder
      - path: Focally/Views/Schedule
        type: folder
      - path: Focally/Views/Analytics
        type: folder
      - path: Focally/Views/Settings
        type: folder
      - path: Focally/Resources
        type: folder
        buildPhase: resources
      - path: Focally/Resources/Fonts
        type: folder
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: Focally/Info.plist
        CODE_SIGN_ENTITLEMENTS: Focally/Focally.entitlements
        PRODUCT_BUNDLE_NAME: Focally
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_COLOR_SET_NAME: focally
        COMBINE_HIDPI_IMAGES: true
        ENABLE_PREVIEWS: true
        SWIFT_EMIT_LOC_STRINGS: true
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: false
    entitlements:
      path: Focally/Focally.entitlements
      properties:
        com.apple.security.automation.apple-events: true
    dependencies: []
